byte:
	g++ client.cpp -o client
	g++ server.cpp -o server
	cls
bit:
	g++ bit_client.cpp -o bclient
	g++ bit_server.cpp -o bserver
clean:
	rm client
	rm server
	cls
bclean:
	rm bclient
	rm bserver
	cls